import { Footer } from '@/components/footer'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Navbar } from '@/components/navbar'

const poppins = Poppins({weight: ['400', '500', '600', '700', '800'], subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
